### ISSUE TITLE
Cocoapods can't find latest version

### ISSUE THREAD

**Issue by fernandodev** [sweetmandm/ionicons-iOS#13]
Hi, 

Current version of ionicons is 2.0.1 but Cocoapods are listing `2.0` only. When `pod install` runs cocoapods try to find version `2.0` and nothing happens.

But if you put `pod 'ionicons', '~> 2.0.1'` in `Podfile` everything works fine. 

Is this a bug?

**Comment by sweetmandm** [comment]
This should work now with either `pod 'ionicons'` or `pod 'ionicons', '~> 2.0.3'`
