### ISSUE TITLE
Ionicons instructions wrong if using dynamic frameworks

### ISSUE THREAD

**Issue by quicklywilliam** [sweetmandm/ionicons-iOS#16]
If you are using dynamic frameworks, the app will not be able to find the font file (because it is in the framework bundle). Adding
```
Frameworks/ionicons.framework/ionicons.ttf
```
to your Info.plist instead fixes it. Readme should be updated to reflect this (using dynamic frameworks with Cocoa Pods is currently all or nothing, which means if any of your pods require it you are going to have to use it with ionicons).

**Comment by sweetmandm** [comment]
Thanks for this, I'll add it to the readme soon!

**Comment by joshdholtz** [comment]
:+1:

**Comment by papcio28** [comment]
:+1:

**Comment by sweetmandm** [comment]
I think this should be solved in 2.0.3 since it's using a resource bundle now and the font name doesn't need to go into the info.plist any more.
